#!/usr/bin/env bash
set -euxo pipefail

scripts=("$PWD"/scripts/*.sh "$PWD"/e2e/{test_,run_}* "$PWD"/e2e/*.sh)

cargo clippy -- -Dwarnings
cargo fmt --all -- --check
shellcheck -x "${scripts[@]}"
shfmt -d -i 0 "${scripts[@]}"
prettier -c $(git ls-files '*.yml' '*.yaml')
markdownlint .
