#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

export MISE_EXPERIMENTAL=1

assert "mise x ubi:zph/polylint@0.0.3 -- polylint -v | head -2 | tail -1" "Version: v0.0.3"
